### ISSUE TITLE
Does v2 of Bittrex API actually exist? Docs? Sources?

### ISSUE THREAD

**Issue by MeoMix** [platelminto/java-bittrex-2#2]
Hey,

There's some discussion over on the Node implementation of Bittrex's API where we're wondering if v2 actually exists. This repo would imply it does... but I see no official (or unofficial!) documentation anywhere on v2.

How come this repo exists?

**Comment by platelminto** [comment]
Hello,

I was told they were close to releasing a v2 implementation of their API, and was provided with the endpoints at the time. This was just after I had released my v1. 1 implementation,  and they mentioned that v2 should be released soon, so I published this wrapper, assuming some minor changes would happen that would easily be fixed, nothing major.

I was wrong. This was over a year ago, and since then v2 has slowly stopped working; I'm assuming they decided to remake it. I've added a message at the top of v2's README saying it's not working correctly and v1.1 should be used instead, with a link to it.

Sorry if this caused any issues - v2 does not yet exist, 1.1 is indeed the most recent version.
